[profile.default]
solc = "0.8.21"
optimizer = true
optimizer_runs = 200

ffi = true
out = ".artifacts/foundry"
script = "scripts"
cache_path = ".cache/foundry"
verbosity = 3
fs_permissions = [
  { access = "read", path = "deployments" },
  { access = "read-write", path = ".cache" },
]

[profile.default.fmt]
bracket_spacing = true
tab_width = 2

[rpc_endpoints]
optimism = "${RPC_URL_HTTP}"
