on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: v0.16.0
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: contracts/requirements.txt

      - run: bun install
      - run: pip install -r contracts/requirements.txt
      - run: npx playwright install chromium webkit --with-deps

      - run: npm test

      - uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: webapp/playwright-report/
